#!/usr/bin/env bash

# Creates the file /var/run/myscript.pid that contains its PID

pid=$(echo $$)
echo $pid > /var/run/myscript.pid

# Displays To infinity and beyond indefinitely

while true; do
  echo "To infinity and beyond!"
  sleep 1
done

# Displays I hate the kill command when receiving a SIGTERM signal

trap 'echo "I hate the kill command!"' SIGTERM

# Displays Y U no love me?! when receiving a SIGINT signal

trap 'echo "Y U no love me?!"' SIGINT

# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

