#!/usr/bin/env bash

#This script parse through the log file and print the ip and http status

awk -F' ' '{ print $1, $9 }' apache-access.log | sort | uniq -c | sort -rn

2-while_best_school

#!/usr/bin/env bash

# This script is displaying "Best School" 10 times

i=0

while ((i < 10))

do

        echo "Best School"

        ((i++))

done
